apiVersion: v1
kind: Service
metadata:
  name: {{ include "gromit-chart.fullname" . }}
  labels:
    {{- include "gromit-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
  selector:
    {{- include "gromit-chart.selectorLabels" . | nindent 4 }}
