apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity
  labels:
    app: nginx
spec:
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
               matchExpressions:
               - key: app
                 operator: In
                 values:
                 - nginx
            topologyKey: kubernetes.io/hostname
  containers:
  - name: node-affinity-pod
    image: nginx:1.25.3
