apiVersion: v1
kind: Service
metadata:
  name: gromit-node-port
spec:
  type: NodePort
  selector:
    app: geo
  ports:
    - name: 7777-port
      protocol: TCP
      port: 8000
      targetPort: 7777
      nodePort: 30001
    - name: 8888-port
      protocol: TCP
      port: 8001
      targetPort: 8888
      nodePort: 30002
